version: 2
job_definition: &job_definition

  working_directory: ~/repo
    
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb
    
  steps:
    - checkout
    
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies-
    
    - run: ./gradlew dependencies
        
    # run tests!
    - run: ./gradlew test
    
    - store_test_results:
        path: build/reports/tests
    
    - save_cache:
        paths:
          - ~/.gradle
          - ./.gradle
        key: v2-dependencies-{{ checksum "build.gradle" }}

jobs:
  openjdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *job_definition
  
  oraclejdk8:
    docker:
      - image: circleci/java:8-jdk
    <<: *job_definition

workflows:
  version: 2
  all:
    jobs:
      - openjdk8
      - oraclejdk8